name: Sleeve COS CI # Actions名称
on:
  # 触发workflow的动作形式 - 手动触发
  workflow_dispatch:
  # 触发workflow的动作形式 - main分支的push操作
  push:
    branches: [main]
  # 触发workflow的动作形式 - main分支的pr操作
  pull_request:
    branches: [main]
jobs:
  build:
    # 当前脚本是在容器中运行的，对应的镜像是ubuntu-latest
    runs-on: ubuntu-latest
    steps:
    # 下载源码
    - name: checkout
      uses: actions/checkout@main
    # 安装依赖
    - name: install
      run: yarn
    # 打包
    - name: build project
      run: yarn run build
    # 打包镜像推送到阿里云容器镜像服务
    - name: Build the Docker image
      run: |
        docker login --username=${{ secrets.DOCKER_USERNAME }} registry.cn-hangzhou.aliyuncs.com --password=${{ secrets.DOCKER_PASSWORD }}
        docker build -t sleeve-cos:latest .
        docker tag sleeve-cos registry.cn-hangzhou.aliyuncs.com/sleeve/sleeve-cos:latest
        docker push registry.cn-hangzhou.aliyuncs.com/sleeve/sleeve-cos:latest
    # 使用appleboy/ssh-action@master登录服务器执行拉取镜像脚本
    - name: ssh docker login
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        script: cd ~ && sh sleeve-deploy/sleeve-cos.sh ${{ secrets.DOCKER_USERNAME }} ${{ secrets.DOCKER_PASSWORD }}
